export enum PAYMENT_STATUS {
  DENIED = "DENIED",
  DUPLICATE = "DUPLICATE",
  FAILED = "FAILED",
  PENDING = "PENDING",
  REFUNDED = "REFUNDED",
  SUCCESS = "SUCCESS",
  TAMPERED = "TAMPERED",
  TEST = "TEST",
}

export enum EXTERNAL_PAYOUT_PAYMENT_STATUS {
  FAILED = "FAILED",
  IN_PROGRESS = "IN_PROGRESS",
  SUCCESS = "SUCCESS",
}

export enum PAYMENT_TYPE {
  PAYIN = "payin",
  PAYOUT = "payout",
  SETTLEMENT = "settlement",
}

export enum CURRENCY_ENUM {
  INR = "INR",
  USD = "USD",
}

export enum PAYOUT_PAYMENT_MODE {
  IMPS = "IMPS",
  NEFT = "NEFT",
  RTGS = "RTGS",
}

export enum SETTLEMENT_STATUS {
  NOT_INITIATED = "NOT_INITIATED",
  INITIATED = "INITIATED",
  SETTLED = "SETTLED",
  FAILED = "FAILED",
}
