export enum PAYMENT_STATUS {
  ABORTED = "ABORTED",
  DEEMED = "DEEMED",
  DENIED = "DENIED",
  DUPLICATE = "DUPLICATE",
  FAILED = "FAILED",
  INITIATED = "INITIATED",
  MISMATCH = "MISMATCH",
  NOT_FOUND = "NOT_FOUND",
  PENDING = "PENDING",
  REFUNDED = "REFUNDED",
  REJECTED = "REJECTED",
  SUCCESS = "SUCCESS",
  TAMPERED = "TAMPERED",
  TEST = "TEST",
}

export enum EXTERNAL_PAYOUT_PAYMENT_STATUS {
  FAILED = "FAILED",
  IN_PROGRESS = "IN_PROGRESS",
  SUCCESS = "SUCCESS",
}

export enum PAYMENT_TYPE {
  PAYIN = "payin",
  PAYOUT = "payout",
  SETTLEMENT = "settlement",
}

export enum CURRENCY_ENUM {
  INR = "INR",
  USD = "USD",
}

export enum PAYOUT_PAYMENT_MODE {
  IMPS = "IMPS",
  NEFT = "NEFT",
  RTGS = "RTGS",
}

export enum SETTLEMENT_STATUS {
  FAILED = "FAILED",
  INITIATED = "INITIATED",
  NOT_INITIATED = "NOT_INITIATED",
  SETTLED = "SETTLED",
}

export enum MODE_OPTIONS {
  IMPS = "IMPS",
  NEFT = "NEFT",
  RTGS = "RTGS",
  UPI = "UPI",
}

export enum ACTIVITY {
  ACTIVE = "ACTIVE",
  BLOCKED = "BLOCKED",
  CANCELLED = "CANCELLED",
  CLOSED = "CLOSED",
  DELETED = "DELETED",
  EXPIRED = "EXPIRED",
  FROZEN = "FROZEN",
  INACTIVE = "INACTIVE",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED",
  TERMINATED = "TERMINATED",
}

export enum PAYIN_WALLET_LOAD_STATUS {
  APPROVED = "APPROVED",
  PENDING = "PENDING",
  REJECTED = "REJECTED",
}
